
import { Metadata } from "next";
import InputForm from "./comonents/InputForm";

export const metadata: Metadata = {
  title: "Home Todo App",
  description: "Generated by create next app",
};
export default function Home() {
  return (
    <div className="w-full min-h-screen bg-gradient-to-r from-slate-100 via-slate-300 to-slate-300 flex items-center justify-center text-gray-400">
    <div className="max-w-screen-md bg-bodyColor p-4 md:p-20 lg:p-10 rounded-md flex flex-col gap-5">
      <InputForm />
    </div>
    </div>
  );
}
